version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_SW_API_BASE=http://localhost:8000/api/v1
    depends_on:
      - backend